
import React, { useState, useRef, useEffect } from 'react';
import { Send, Bot, User, Sparkles, ChevronDown, Activity, CheckCircle2, CircleDashed } from 'lucide-react';
import { IRIS_TEAMS } from '../constants';
import { IrisTeamMember, ChatMessage } from '../types';
import { geminiService } from '../services/geminiService';
import { useStore } from '../context/StoreContext';

export const IrisAI: React.FC = () => {
  const { addTask, user } = useStore();
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'model',
      content: 'Hello Admin. I am the Chief Orchestrator. I can plan complex projects and assign tasks to specialized agents. What do you need done today?',
      timestamp: new Date()
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isThinking, setIsThinking] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!inputValue.trim()) return;

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMsg]);
    setInputValue('');
    setIsThinking(true);

    // Call Orchestrator Service
    const { text, steps } = await geminiService.orchestrateRequest(userMsg.content);

    // Simulate Step-by-Step Execution UI
    if (steps.length > 0) {
       // Create a temporary "Orchestrating" message
       const orchId = (Date.now() + 1).toString();
       const orchMsg: ChatMessage = {
          id: orchId,
          role: 'model',
          content: 'Orchestrating plan...',
          timestamp: new Date(),
          isOrchestration: true,
          orchestrationSteps: steps.map((s: any) => ({ step: `[${s.assignedTeam}] ${s.step}`, status: 'pending' }))
       };
       setMessages(prev => [...prev, orchMsg]);
       
       // Animate steps finishing
       for (let i = 0; i < steps.length; i++) {
          await new Promise(r => setTimeout(r, 1000)); // Fake delay
          setMessages(prev => prev.map(m => {
             if (m.id === orchId && m.orchestrationSteps) {
                const newSteps = [...m.orchestrationSteps];
                newSteps[i].status = 'completed';
                if (i + 1 < newSteps.length) newSteps[i+1].status = 'active';
                return { ...m, orchestrationSteps: newSteps };
             }
             return m;
          }));
          
          // Actually create tasks in the "backend"
          addTask({
             title: `[AI] ${steps[i].step}`,
             description: `Generated by Orchestrator for ${steps[i].assignedTeam}`,
             assignee: user.id, // Assign to admin for review in this demo
             priority: 'MEDIUM',
             generatedByAI: true
          });
       }
       
       // Final Text Response
       const finalMsg: ChatMessage = {
         id: (Date.now() + 2).toString(),
         role: 'model',
         content: text,
         timestamp: new Date()
       };
       setMessages(prev => [...prev, finalMsg]);
    } else {
       // Fallback for simple chat
       const simpleResp = await geminiService.generateResponse(userMsg.content, messages, IRIS_TEAMS[0]);
       setMessages(prev => [...prev, {
         id: (Date.now() + 1).toString(),
         role: 'model',
         content: simpleResp,
         timestamp: new Date()
       }]);
    }

    setIsThinking(false);
  };

  return (
    <div className="flex flex-col h-full bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
      {/* Header */}
      <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-slate-900 text-white">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-brand-500/20 rounded-lg text-brand-400">
            <Activity size={20} />
          </div>
          <div>
            <h2 className="font-semibold text-white">Orchestrator Engine</h2>
            <p className="text-xs text-slate-400">Coordinating 6 Specialized Teams</p>
          </div>
        </div>
      </div>

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-6 bg-slate-50/50 custom-scroll">
        {messages.map((msg) => (
          <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`flex gap-3 max-w-[85%] ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
              <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${msg.role === 'user' ? 'bg-slate-200' : 'bg-brand-600 text-white'}`}>
                {msg.role === 'user' ? <User size={16} className="text-slate-600"/> : <Bot size={16} />}
              </div>
              
              <div className="flex flex-col gap-1 w-full">
                {/* Orchestration Visualizer */}
                {msg.isOrchestration && msg.orchestrationSteps ? (
                   <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm w-full">
                      <div className="text-xs font-bold text-slate-500 uppercase mb-3 flex items-center gap-2">
                         <Activity size={14} className="text-brand-500"/> Execution Plan
                      </div>
                      <div className="space-y-3">
                         {msg.orchestrationSteps.map((step, idx) => (
                            <div key={idx} className="flex items-start gap-3 text-sm">
                               <div className="mt-0.5">
                                  {step.status === 'completed' ? <CheckCircle2 size={16} className="text-emerald-500"/> : 
                                   step.status === 'active' ? <div className="w-4 h-4 border-2 border-brand-500 border-t-transparent rounded-full animate-spin"/> :
                                   <CircleDashed size={16} className="text-slate-300"/>}
                               </div>
                               <span className={`${step.status === 'completed' ? 'text-slate-700' : step.status === 'active' ? 'text-brand-700 font-medium' : 'text-slate-400'}`}>
                                  {step.step}
                               </span>
                            </div>
                         ))}
                      </div>
                   </div>
                ) : (
                  <div className={`p-3 rounded-2xl text-sm leading-relaxed shadow-sm ${
                    msg.role === 'user' 
                      ? 'bg-slate-800 text-white rounded-tr-none' 
                      : 'bg-white border border-slate-200 text-slate-700 rounded-tl-none'
                  }`}>
                    {msg.content}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
        {isThinking && (
          <div className="flex justify-start">
             <div className="flex gap-3">
              <div className="w-8 h-8 rounded-full bg-brand-600 text-white flex items-center justify-center">
                <Bot size={16} />
              </div>
              <div className="bg-white border border-slate-200 px-4 py-3 rounded-2xl rounded-tl-none shadow-sm flex items-center gap-2">
                 <span className="w-2 h-2 bg-brand-400 rounded-full animate-bounce"></span>
                 <span className="text-xs text-slate-500 font-medium">Analyzing Intent...</span>
              </div>
             </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-4 bg-white border-t border-slate-100">
        <div className="flex gap-2">
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Describe a project or task for the team..."
            className="flex-1 bg-slate-50 border border-slate-200 text-slate-900 text-sm rounded-xl focus:ring-2 focus:ring-brand-500 focus:border-transparent block w-full p-2.5 outline-none transition-all"
          />
          <button 
            onClick={handleSend}
            disabled={!inputValue.trim() || isThinking}
            className="p-2.5 bg-brand-600 text-white rounded-xl hover:bg-brand-700 disabled:opacity-50 transition-colors shadow-sm"
          >
            <Send size={20} />
          </button>
        </div>
      </div>
    </div>
  );
};
